### PR TITLE
Set up a "Hello world" project with rails-react gem

### PR DESCRIPTION
**Pull request by IjayAbby**
#### Project requirement.

-     Create a new Rails app called 'hello-rails-react'.
-     Initialize your project with Git.
-     Set up your project with web-packer the react-rails gems as describe in the previous lesson's tutorial.
-     Make sure that your project has a Postgres database set up.
-     Create a table for storing your messages and create 5 different greetings.
-     Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and       Rails route).
-     Create a static view that will be the root of your app.
-     Create the App component with react-router and render it in your static view.
-     Create the Greeting component that will display a greeting. Set it up as a route in your App component.
-     Create a store, an action and a reducer that will connect to you API end-point to get the random greeting.
-     Display the random greeting in your Greeting component.

### CODE REVIEW

**Comment by DeliceLydia** [comment]
# Hello @IjayAbby,

Unfortunately I can't review your project because you did not add 
linter setup please add them and ask another CRR

Thanks

**Review by oxenprogrammer — CHANGES_REQUESTED** [review]
Hi @IjayAbby, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses a different `linters.yml`. Please use [this linters.yml file](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml). 
Once you push, please cross check that you have `two passing checks`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DeliceLydia** [comment]
## Hi @IjayAbby,

I can see that you removed linters for styling
and I know you will need it in this project please
set it up you can follow this [link](https://github.com/microverseinc/linters-config)
and submit another CRR.

Thanks!

**Review by DeliceLydia — APPROVED** [review]
# Congratulations🎉🎉

## Hi @IjayAbby, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Optional
- Next time you can improve your PR writings checkout this [link](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)




### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
